FROM debian:9-slim

RUN apt-get update && apt-get install -y wget

RUN mkdir /opt/cmake-3.3.2 \
    && cd /opt/cmake-3.3.2 \
    && wget --no-verbose https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.3.2-Linux-x86_64.tar.gz \
    && rm cmake-3.3.2-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.4.3 \
    && cd /opt/cmake-3.4.3 \
    && wget --no-verbose https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.4.3-Linux-x86_64.tar.gz \
    && rm cmake-3.4.3-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.5.2 \
    && cd /opt/cmake-3.5.2 \
    && wget --no-verbose https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.5.2-Linux-x86_64.tar.gz \
    && rm cmake-3.5.2-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.6.3 \
    && cd /opt/cmake-3.6.3 \
    && wget --no-verbose https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.6.3-Linux-x86_64.tar.gz \
    && rm cmake-3.6.3-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.7.2 \
    && cd /opt/cmake-3.7.2 \
    && wget --no-verbose https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.7.2-Linux-x86_64.tar.gz \
    && rm cmake-3.7.2-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.8.2 \
    && cd /opt/cmake-3.8.2 \
    && wget --no-verbose https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.8.2-Linux-x86_64.tar.gz \
    && rm cmake-3.8.2-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.9.6 \
    && cd /opt/cmake-3.9.6 \
    && wget --no-verbose https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.9.6-Linux-x86_64.tar.gz \
    && rm cmake-3.9.6-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.10.3 \
    && cd /opt/cmake-3.10.3 \
    && wget --no-verbose https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.10.3-Linux-x86_64.tar.gz \
    && rm cmake-3.10.3-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.11.4 \
    && cd /opt/cmake-3.11.4 \
    && wget --no-verbose https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.11.4-Linux-x86_64.tar.gz \
    && rm cmake-3.11.4-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.12.4 \
    && cd /opt/cmake-3.12.4 \
    && wget --no-verbose https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.12.4-Linux-x86_64.tar.gz \
    && rm cmake-3.12.4-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.13.5 \
    && cd /opt/cmake-3.13.5 \
    && wget --no-verbose https://cmake.org/files/v3.13/cmake-3.13.5-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.13.5-Linux-x86_64.tar.gz \
    && rm cmake-3.13.5-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.14.7 \
    && cd /opt/cmake-3.14.7 \
    && wget --no-verbose https://cmake.org/files/v3.14/cmake-3.14.7-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.14.7-Linux-x86_64.tar.gz \
    && rm cmake-3.14.7-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.15.7 \
    && cd /opt/cmake-3.15.7 \
    && wget --no-verbose https://cmake.org/files/v3.15/cmake-3.15.7-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.15.7-Linux-x86_64.tar.gz \
    && rm cmake-3.15.7-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.16.9 \
    && cd /opt/cmake-3.16.9 \
    && wget --no-verbose https://cmake.org/files/v3.16/cmake-3.16.9-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.16.9-Linux-x86_64.tar.gz \
    && rm cmake-3.16.9-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.17.5 \
    && cd /opt/cmake-3.17.5 \
    && wget --no-verbose https://cmake.org/files/v3.17/cmake-3.17.5-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.17.5-Linux-x86_64.tar.gz \
    && rm cmake-3.17.5-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.18.6 \
    && cd /opt/cmake-3.18.6 \
    && wget --no-verbose https://cmake.org/files/v3.18/cmake-3.18.6-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.18.6-Linux-x86_64.tar.gz \
    && rm cmake-3.18.6-Linux-x86_64.tar.gz \
    && ./bin/cmake --version

RUN mkdir /opt/cmake-3.19.8 \
    && cd /opt/cmake-3.19.8 \
    && wget --no-verbose https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz \
    && tar --extract --gzip --strip-components=1 --file=cmake-3.19.8-Linux-x86_64.tar.gz \
    && rm cmake-3.19.8-Linux-x86_64.tar.gz \
    && ./bin/cmake --version
